
import { _decorator, Component } from 'cc';
import gameCommonUtils from '../../../../cc-common/cc-share/common/gameCommonUtils';
const { ccclass } = _decorator;

@ccclass('Config8000')
export class Config8000 extends Component {
    onLoad() {
        (this.node as any).config = {
            GAME_ID: '8000',
            JP_PREFIX_EVENT: '8000_',
            JP_NAMES: ["GRAND"],
            USE_SHORT_PARAM: false,
            DEFAULT_BET: "1",
            BETS: {
                '1': 500,
                '2': 1000,
                '3': 5000,
                '4': 10000,
                '5': 50000,
                '6': 500000,
            },
            DEFAULT_EXTRA_BET: "0",
            EXTRA_BETS: {
                "0": 1
            },
            TOTAL_BET_CREDIT: 25,
            TREASURE_VALUE_1: ["1", "2", "3", "4"],
            DEFAULT_TRIAL_JACKPOT: {
                "8000_1_GRAND": 250000,
                "8000_2_GRAND": 500000,
                "8000_3_GRAND": 2500000,
                "8000_4_GRAND": 5000000,
                "8000_5_GRAND": 25000000,
                "8000_6_GRAND": 250000000,
            },
            DEFAULT_TRIAL_WALLET: 200000000,
            TRIAL_BET: '5',
            TRIAL_EXTRA_BET: '0',
            MESSAGE_DIALOG: gameCommonUtils.getMessageSlot(),
            DEMONTATION: 250,
            ACTIVE_SYMBOL: ["8", "18", "38", "68", "168"],
            BOX_MAP_VALUES: {
                100: 1,
                200: 2,
                400: 3
            },
            RANDOM_ACTIVE_SYMBOL: [
                ["8"],
                ["8", "18"],
                ["8", "18", "38"],
                ["8", "18", "38", "68"],
                ["8", "18", "38", "68", "168"],
            ],
            BEAUTY_MATRIX: [
                // "10,3,K3,9,7,3,8,R,10,4,5,9,K3,4,8",
                // "7,7,10,7,A,J,10,J,8,J,A,6,8,6,6",
                "7,3,7,6,K1,6,9,9,9,6,K2,6,6,4,6"
            ],
            PAY_TABLE: {
                "2": [10, 15, 50],
                "3": [5, 10, 20],
                "4": [5, 10, 20],
                "5": [5, 10, 20],
                "6": [5, 10, 20],
                "22": [10, 15, 50],
                "33": [35, 65, 250],
                "44": [15, 50, 200],
                "55": [15, 35, 150],
                "66": [10, 30, 100],
            },
            GAME_SPEED: {
                NORMAL: 0,
                TURBO: 1,
                INSTANTLY: 2,
            },
            PARTICLE_MOVING_TIME: 1,
            MUSIC_VOLUME: 0.7,
            SOUND_EFFECT_VOLUME: 1,
            JP_LIST_HISTORY: 'GRAND-MAJOR',
            BET_IDS: "10-20-30-40-50-60",
            BET_IDS_IFRAME: "10-20-30-40-50-60",
            SKIP_NEAR_WIN_TURBO: true,
            IS_SHOW_JACKPOT_EXPLOSION: true,

            HIGH_PERFORMANCE_LV: {
                PAYLINE_ANIMATION: 2,
                BIG_WIN_ANIMATION: 2,
                JP_WIN_ANIMATION: 2,
                BACKGROUND_ANIMATION: 2,
                NEAR_WIN_ANIMATION: 2,
                TRANSITION_ANIMATION: 2,
                BONUS_ANIMATION: 2,
            },

            MEDIUM_PERFORMANCE_LV: {
                PAYLINE_ANIMATION: 1,
                BIG_WIN_ANIMATION: 1,
                JP_WIN_ANIMATION: 1,
                BACKGROUND_ANIMATION: 1,
                NEAR_WIN_ANIMATION: 1,
                TRANSITION_ANIMATION: 1,
                BONUS_ANIMATION: 1,
            },

            LOW_PERFORMANCE_LV: {
                PAYLINE_ANIMATION: 0,
                BIG_WIN_ANIMATION: 0,
                JP_WIN_ANIMATION: 0,
                BACKGROUND_ANIMATION: 0,
                NEAR_WIN_ANIMATION: 0,
                TRANSITION_ANIMATION: 0,
                BONUS_ANIMATION: 0,
            },
            /********** * ONLY TABLE CONFIG ****************/
            NORMAL_TABLE_FORMAT: [3, 3, 3, 3, 3],
            FREE_TABLE_FORMAT: [3, 3, 3, 3, 3],
            TOPUP_TABLE_FORMAT: [3, 3, 3, 3, 3],
            BONUS_TABLE_FORMAT: [3, 3, 3, 3, 3],
            TABLE_BUFFER: {
                TOP: 1,
                BOT: 1,
            },
            ACCEL: 1200,
            MIN_SPEED: 2000,
            MAX_SPEED: 2800,
            SUPER_SPEED: 3500,
            SUPER_TURBO: 0.05,
            TABLE_NORMAL: {
                TIME: 0.06,
                DELAY_START: 0,
                DELAY_STOP: 0.2,
                EASING_DISTANCE: 15,
                EASING_TIME: 0.5,
                TOTAL_CIRCULAR: 8,
                STEP_STOP: 12,
                RATE: 1,
                IS_TURBO: false,
                BLINKS: 2,
                BLINK_DURATION: 0.5,
                ANIMATION_DURATION: 2,
                EXPECT_PAYLINE_TIME: 2,
                EXPECT_PAYLINE_ALLWAYS_TIME: 2,
                MIN_TIME_EACH_PAYLINE: 0.3,
                NEAR_WIN_DELAY: 0.4,
                NEAR_WIN_DELAY_LAST_REEL: 1
            },
            TABLE_TURBO: {
                TIME: 0.06,
                DELAY_START: 0,
                DELAY_STOP: 0.1,
                EASING_DISTANCE: 15,
                EASING_TIME: 0,
                TOTAL_CIRCULAR: 6,
                STEP_STOP: 8,
                RATE: 2,
                IS_TURBO: true,
                BLINKS: 1,
                BLINK_DURATION: 0.5,
                ANIMATION_DURATION: 2,
                EXPECT_PAYLINE_TIME: 2,
                EXPECT_PAYLINE_ALLWAYS_TIME: 2,
                MIN_TIME_EACH_PAYLINE: 0.2,
                NEAR_WIN_DELAY: 0.2,
                NEAR_WIN_DELAY_LAST_REEL: 1
            },
            NORMAL_SYMBOLS: [
                ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'K', 'A', 'R'],
                ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'K1', 'A', 'R'],
                ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'K', 'A', 'R'],
                ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'K2', 'A', 'R'],
                ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'K', 'A', 'R'],
            ],
            FREE_SYMBOLS: [
                ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'K', 'A', 'R'],
                ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'K1', 'A', 'R'],
                ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'K', 'A', 'R'],
                ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'K2', 'A', 'R'],
                ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'K', 'A', 'R'],
            ],

            EXCEPTION_SYMBOLS: ["A", "R", "K", "K1", "K2"],
            WILD_SYMBOL: 'K',
            WILD_SYMBOLS: ['K1', 'K2', 'K3'],
            SYMBOL_SMALL_NAME_LIST: ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J'],
            SYMBOL_WIDTH: 170,
            SYMBOL_HEIGHT: 158,
            SYMBOL_BONUS_WIDTH: 150,
            SYMBOL_BONUS_HEIGHT: 150,
            PAY_LINE_LENGTH: 20,
            PAY_LINE_ALLWAYS: false,
            SHOW_WINLINE_FRAME: true,
            SHOW_DRAWING_LINE: true,
            PAY_LINE_MATRIX: {
                "1": [1, 1, 1, 1, 1],
                "2": [0, 0, 0, 0, 0],
                "3": [2, 2, 2, 2, 2],
                "4": [0, 1, 2, 1, 0],
                "5": [2, 1, 0, 1, 2],
                "6": [1, 0, 1, 0, 1],
                "7": [1, 2, 1, 2, 1],
                "8": [0, 1, 0, 1, 0],
                "9": [2, 1, 2, 1, 2],
                "10": [1, 0, 0, 0, 1],
                "11": [1, 2, 2, 2, 1],
                "12": [2, 2, 1, 2, 2],
                "13": [0, 0, 1, 0, 0],
                "14": [2, 1, 1, 1, 2],
                "15": [0, 1, 1, 1, 0],
                "16": [0, 2, 0, 2, 0],
                "17": [2, 0, 2, 0, 2],
                "18": [1, 1, 0, 1, 1],
                "19": [1, 1, 2, 1, 1],
                "20": [2, 2, 0, 2, 2],
            },
            DEFAULT_BONUS_MATRIX: [-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
            HAS_GAME_EVENT: false,
            SERVER_VERSION: '',
            TIME_COUNT_WIN_AMOUNT: { 1: 0, 2: 0, 3: 4, 4: 6 },
            TIME_WIN: { 1: 0, 2: 0, 3: 5, 4: 7 },

            /********** * ONLY FOR TUTORIAL ****************/
            TUTORIAL_TEXT: {
                CLICK_SPIN_1: "Bấm quay để bắt đầu chơi.",
                INFO_BET_1: "Xét trên dòng 1 đang cược 5K, có 3 \nbiểu tượng Eva và hệ số thưởng là\n 40 thì sẽ được trả thưởng\n là 5K x 40 = 200.000.",
                INTRO_JACKPOT: "Đây là hũ xu của game, mỗi lần quay sẽ góp 1 phần tiền cược vào hũ.",
                CONTINUE_SPIN: "Thử thêm lần nữa nào.",
                CLICK_BET: "Không thắng được gì. Thử tăng mức cược lên xem sao.",
                CLICK_TURBO: "Bấm vào đây để tăng tốc.",
                WIN_BONUS: "Tìm đủ 3 biểu tượng Bonus, bạn sẽ \nbiết được đường vào hầm bí mật.",
                BONUS_RULE: "Bạn có 3 lần mở rương với các phần thưởng khác nhau. Hãy chọn nào.",
                WIN_SCATTER: "Tìm đủ 3 biểu tượng Free bạn sẽ bắt được tín hiệu trợ giúp.",
                SPIN_TIMES: "Số lần quay còn lại sẽ được cập nhật ở đây.",
                CLICK_AUTO_SPIN: "Nhấn giữ để tự động quay."
            }
        };
    }
}